name: Build Release
on:
  push:
    branches:
      - release/*
jobs:
  build:
    if: "startsWith(github.event.head_commit.message, 'Release')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }}

      - name: Build with Gradle
        run: gradle jar

      - name: "Prepare Release"
        run: |
          RELEASE_VERSION=$(gradle -q getVersion)
          RELEASE_BRANCH_NAME=$(gradle -q getReleaseBranchName -Dversion="$RELEASE_VERSION")
          
          echo "BRANCH_NAME=$RELEASE_BRANCH_NAME" >> $GITHUB_ENV
          echo "VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: "Create Release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/libs/*.jar
          name: Release ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          commit: release/${{ env.BRANCH_NAME }}