# Trigger via gh cli:
# gh workflow run trigger_patch_release.yml
name: Trigger Patch Release
on:
  workflow_dispatch:
jobs:
  trigger_patch_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }}

      - name: "merge changes to latest release branch and trigger patch release"
        run: |
          git config --global user.email "action@github"
          git config --global user.name "Trigger Release Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          
          SCRIPTS_DIR=".github/workflows/scripts/"
          sh "$SCRIPTS_DIR/get_latest_tag.sh"
          LAST_RELEASE=$(sh "$SCRIPTS_DIR/get_latest_tag.sh")
          echo "Last Release was: $LAST_RELEASE"
          NEW_VERSION=$(sh "$SCRIPTS_DIR/increase_patch_version.sh" "$LAST_RELEASE")
          gradle -q setVersion -Dversion="$NEW_VERSION"
          
          RELEASE_VERSION=$(gradle -q getVersionWithoutSnapshot)
          RELEASE_BRANCH_NAME=$(gradle -q getReleaseBranchName -Dversion="$RELEASE_VERSION")
          RELEASE_BRANCH="release/$RELEASE_BRANCH_NAME"
        
          echo "Release Version: $RELEASE_VERSION"
          git stash
          git checkout $RELEASE_BRANCH
          git merge --strategy-option theirs --allow-unrelated-histories --no-edit dev
          git push
          
          gradle -q setVersion -Dversion="$RELEASE_VERSION"
          git commit -a -m "Release $RELEASE_VERSION"
          git push